_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 5
                - 51
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 51
                - 53
                - 55
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 16
classifier:
    value: all_patch_reps_twolayer
clip_value:
    value: 1
cuda:
    value: 0
datasets_dir:
    value: /mnt/disk1/aiotlab/namth/EEGFoundationModel/datasets/pearl_30s
downstream_dataset:
    value: PEARL
dropout:
    value: 0.1
epochs:
    value: 20
foundation_dir:
    value: pretrained_weights/pretrained_weights.pth
frozen:
    value: false
label_smoothing:
    value: 0.1
lr:
    value: 0.0003
modality_mode:
    value: multi_attend
model_dir:
    value: ./data/wjq/models_weights/Big/BigFaced
multi_lr:
    value: false
num_folds:
    value: -1
num_of_classes:
    value: 2
num_workers:
    value: 16
optimizer:
    value: AdamW
project_name:
    value: EEG_HUST_MULTIMODALITY
seed:
    value: 42
use_pretrained_weights:
    value: true
weight_decay:
    value: 0.05
