_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 5
                - 51
                - 53
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
