_wandb:
    value:
        cli_version: 0.21.4
        e:
            jb0hhwhzhleazusz2zahfqwi7hok223o:
                args:
                    - --epochs
                    - "50"
                    - --batch_size
                    - "16"
                    - --lr
                    - "3e-4"
                    - --downstream_dataset
                    - PEARL
                    - --datasets_dir
                    - /mnt/disk1/aiotlab/namth/EEGFoundationModel/datasets/pearl_30s
                    - --num_of_classes
                    - "2"
                    - --modality_mode
                    - multi_attend
                    - --project_name
                    - EEG_HUST_MULTIMODALITY2
                    - --classifier
                    - all_patch_reps_twolayer
                    - --foundation_dir
                    - /mnt/disk1/aiotlab/namth/EEGFoundationModel/CBraMod/pretrained_weights/pretrained_108.pth
                codePath: finetune_kfold_pearl.py
                codePathLocal: finetune_kfold_pearl.py
                cpu_count: 20
                cpu_count_logical: 40
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "943412031488"
                        used: "705755607040"
                email: nam.th180805@gmail.com
                executable: /mnt/disk1/aiotlab/envs/cbramod/bin/python
                git:
                    commit: 7b463f69cd560205b5d4d061bc8f3a2b5906eba1
                    remote: https://github.com/wjq-learning/CBraMod.git
                gpu: NVIDIA A30
                gpu_count: 3
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3584
                      memoryTotal: "25769803776"
                      name: NVIDIA A30
                      uuid: GPU-97533177-ae5d-752f-8fac-73c43a1a67cc
                    - architecture: Ampere
                      cudaCores: 3584
                      memoryTotal: "25769803776"
                      name: NVIDIA A30
                      uuid: GPU-b71aa699-b956-12eb-ded3-7590ec6c9937
                    - architecture: Ampere
                      cudaCores: 3584
                      memoryTotal: "25769803776"
                      name: NVIDIA A30
                      uuid: GPU-1ae02fa8-11a1-fd0d-1711-434d9c42d9ef
                host: gpus-Super-Server
                memory:
                    total: "134794272768"
                os: Linux-6.8.0-65-generic-x86_64-with-glibc2.35
                program: /mnt/disk1/aiotlab/namth/EEGFoundationModel/CBraMod/finetune_kfold_pearl.py
                python: CPython 3.12.11
                root: /mnt/disk1/aiotlab/namth/EEGFoundationModel/CBraMod
                startedAt: "2025-09-17T06:32:59.408247Z"
                writerId: jb0hhwhzhleazusz2zahfqwi7hok223o
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 51
                - 53
            "2":
                - 1
                - 5
                - 51
                - 53
            "3":
                - 13
                - 16
                - 61
            "4": 3.12.11
            "5": 0.21.4
            "12": 0.21.4
            "13": linux-x86_64
batch_size:
    value: 16
classifier:
    value: all_patch_reps_twolayer
clip_value:
    value: 1
cuda:
    value: 0
datasets_dir:
    value: /mnt/disk1/aiotlab/namth/EEGFoundationModel/datasets/pearl_30s/fold_0
downstream_dataset:
    value: PEARL
dropout:
    value: 0.1
epochs:
    value: 50
foundation_dir:
    value: /mnt/disk1/aiotlab/namth/EEGFoundationModel/CBraMod/pretrained_weights/pretrained_108.pth
frozen:
    value: false
label_smoothing:
    value: 0.1
lr:
    value: 0.0003
modality_mode:
    value: multi_attend
model_dir:
    value: ./data/wjq/models_weights/Big/BigFaced
multi_lr:
    value: false
num_folds:
    value: -1
num_of_classes:
    value: 2
num_workers:
    value: 16
optimizer:
    value: AdamW
project_name:
    value: EEG_HUST_MULTIMODALITY2
seed:
    value: 3407
use_pretrained_weights:
    value: true
weight_decay:
    value: 0.05
