_wandb:
    value:
        cli_version: 0.21.1
        e:
            ukgn3pi20av422nsqnssu5zfq2o2ptjj:
                args:
                    - --lr
                    - "3e-4"
                    - --downstream_dataset
                    - PEARL
                    - --datasets_dir
                    - /mnt/disk1/aiotlab/namth/EEGFoundationModel/datasets/pearl
                    - --num_of_classes
                    - "2"
                    - --epochs
                    - "20"
                codePath: finetune_kfold_pearl.py
                codePathLocal: finetune_kfold_pearl.py
                email: nam.th180805@gmail.com
                executable: /mnt/disk1/aiotlab/envs/hoainiem/bin/python
                git:
                    commit: 7b463f69cd560205b5d4d061bc8f3a2b5906eba1
                    remote: https://github.com/wjq-learning/CBraMod.git
                host: gpus-Super-Server
                os: Linux-6.8.0-65-generic-x86_64-with-glibc2.35
                program: /mnt/disk1/aiotlab/namth/EEGFoundationModel/CBraMod/finetune_kfold_pearl.py
                python: CPython 3.12.11
                root: /mnt/disk1/aiotlab/namth/EEGFoundationModel/CBraMod
                startedAt: "2025-09-12T18:03:14.988096Z"
                writerId: ukgn3pi20av422nsqnssu5zfq2o2ptjj
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 51
                - 53
            "2":
                - 1
                - 5
                - 51
                - 53
            "3":
                - 13
                - 16
                - 24
            "4": 3.12.11
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
batch_size:
    value: 64
classifier:
    value: all_patch_reps
clip_value:
    value: 1
cuda:
    value: 0
datasets_dir:
    value: /mnt/disk1/aiotlab/namth/EEGFoundationModel/datasets/pearl
downstream_dataset:
    value: PEARL
dropout:
    value: 0.1
epochs:
    value: 20
foundation_dir:
    value: pretrained_weights/pretrained_weights.pth
frozen:
    value: false
label_smoothing:
    value: 0.1
lr:
    value: 0.0003
model_dir:
    value: ./data/wjq/models_weights/Big/BigFaced
multi_lr:
    value: false
num_of_classes:
    value: 2
num_workers:
    value: 16
optimizer:
    value: AdamW
seed:
    value: 3407
use_pretrained_weights:
    value: true
weight_decay:
    value: 0.05
